### ISSUE TITLE
Transactions show up as addresses in YAML

### ISSUE THREAD

**Issue by xenog** [haskoin/haskoin-wallet#105]
```yaml
maxpage: 119
addresses:
- tx: 01000000061b89910b9328f07812585b36a5723a0e9755b3df5e0d7ab6b82ac5d323563bae000000006a4730440220088c07e5cccc23d9be12e8ee115c44a79be0acef3e4db563bf7a2718c5556a8302207faa246f3f7dd911be9dd6b9d218ff4eaae7171d80423596d94430b4a78588740121028b0492c132eab8951f316ebe43a585dbf367a823cbcc2afe6735c52bca783bedffffffffef351f406b08d2751d4444f80448cc37b4b95b164a4d4653e76aaf6d181ef6f8000000006a47304402201590231b179e28e412f277fdffc547a8761b7ea64f6325ef0a768941acfdffab022058e7b2dcd1e656fb3e885c8a42863c62ff50d1dd0d1f03c166d16dacfcd405b601210277b4a57ae9ffb22d1a281d1f08c52f9353333c650af322db32f5a4b0d1f3e179ffffffff7097ada44808e699a567c8343766c8aff4290b0d83971bb8c1fe2c0c
a48dcc26000000006a47304402200d394e9cf6d86d0a66b3cabaa2c67f4a3a3067537635ae51f1604125028fd09e0220051af692b13933c8913c9b271de0212d54c8
8a03282613152cb6235334da7975012103adf290718fc0887ee9fcb1798bc8919628c4e97098fb09c30cace4ce347a7969ffffffff88c952cc498977cc239f2ff7e9
df48f6d9a6bd493e2333b3f43e7277d87966fb000000006a4730440220480ac563dd9b49b2fab28b0535d7b3cb036928723244cdf795989c7f8d9e522f02207d2aa4
7771a76ab5b247e506486b4eb49ffaa517acd1102630283552703c83210121024dcaa255a90c1fb8430bfd88292320f01b0d54144bc921541442da6fe182bb90ffff
ffffcc12c95412d0fc6fbc0ed5fee292834306b064da2e57538ad431c80367e488a2000000006a4730440220718ecb8432864bb463d54028222eb29aa3de2f71fb98
8574d211a6a6c8d0fa45022010913781b48e31b24ce92ec65b4f9f29f4c3f4007002b12d230761faa2c6b3e50121028ada43ac277f7cf234d6f477fca633f88adcfa
f37d839053d527ab1695fc0e6affffffffad83e00cbe9268b8171b468b7cc5f3b64580d163212b811a1e6299041d3fc196000000006b4830450221009fba55c3934f
a854a7ce58e7f321b807bebb5cca54549ab7460f0c05e5310ba202203acd5e4e8b2a5db8df7ed5d899bcd964fdaf3852ef068d07412cd8111af1c2cb012103f53ccd
21b9c021872d3c291eb4408f122a890ad006208244b1daef4e27919d28ffffffff01e13da123000000001976a9141d231903ad2e8fac8274f3bb6995c10b6d952a4d
88ac00000000
  invalue: 597769697
  confirmeddate: 1434653851
  hash: 4984987b58792d23d4f52a2bf910d43f0108046d1e3ccd62571f9360d048d56a
  outvalue: 0
  created: 2015-06-18T19:12:37.000Z
  to:
  - miB1wFPar9oahshieRNYkXmrkNdsxujXQy
  value: 597769697
  from:
  - mrpituYgkENWtFo1T3gdRdv5ZuMVMG8R4z
  - mrm2JwoVzFwNbFVNdqiLHvTbiE6bbPmmdy
  - myiKmAVgb8JYzrNbYZDtHiN7YYh1q3KNmN
  - n1Mqceq21pipPwcAfX7S6rMXvp4koMPMvb
  - mimdcF3G26WsMLXFBrEcPkDVzFZdX3K76c
  - mwz65kNop9pdJwGz8npTiDT5GddqwzaZQ3
  accountname: faucet2
  change: []
  confidence: TxBuilding
  confirmedheight: 483042
  iscoinbase: false
  confirmations: 11
  keyringname: main
  confirmedby: 0000000000005df1c9599c221daad42e752da0021bcacbb29329ce3713060af6
  type: incoming
  nosighash: ce4d75e9bd0a5abc01f2d1ceb116dc07a76be563ac7f3b4f1a06af95e02a884a
```
